window.SpriteTypes = {
    anima: "anima",
    aquis: "aquis",
    planta: "planta",
    sprit: "spirit",
}

window.Sprites = {
    "an001": {
        name: "Salem",
        description: "A sleek black cat with enchanting purple eyes",
        type: SpriteTypes.anima,
        src: "./images/sprites/spBlackCat.png",
        icon: "./images/icons/animaSymbol.png",
        actions: [ "damage2", "damage1", "hugsStatus"],
    },
    "an002": {
        name: "Golden Sparkler",
        description: "A glowing firefly with a radiant golden aura",
        type: SpriteTypes.anima,
        src: "./images/sprites/spFirefly.png",
        icon: "./images/icons/animaSymbol.png",
        actions: [ "stubsStatus", "hugsStatus2"],
    },
    "aq001": {
        name: "Crabby",
        description: "An adorable-looking crab with large, sharp claws",
        type: SpriteTypes.aquis,
        src: "./images/sprites/spCrab.png",
        icon: "./images/icons/aquisSymbol.png",
        actions: [ "tackle2", "damage4", "stubsStatus2"],
    },
    "aq002": {
        name: "Asteroidea",
        description: "A gentle and nurturing starfish with shimmering, iridescent arms.",
        type: SpriteTypes.aquis,
        src: "./images/sprites/spStarfish.png",
        icon: "./images/icons/aquisSymbol.png",
        actions: [ "damage4", "tackle3", "stubsStatus2"],
    },
    "pl001": {
        name: "Lilac",
        description: " A delicate pink flower with a sweet, floral fragrance and a delicate soul",
        type: SpriteTypes.planta,
        src: "./images/sprites/spPinkFlower.png",
        icon: "./images/icons/plantaSymbol.png",
        actions: [ "stubsStatus", "damage3", "damage1"],
    },
    "pl002": {
        name: "Vynn",
        description: "A towering vine monster that acts as a fierce protector",
        type: SpriteTypes.planta,
        src: "./images/sprites/spVineMonster.png",
        icon: "./images/icons/plantaSymbol.png",
        actions: ["damage3", "damage1"],
    },
    "sp001": {
        name: "Alastor",
        description: "A small blue spirit with a playful and mischievous nature",
        type: SpriteTypes.sprit,
        src: "./images/sprites/spBlueSpirit.png",
        icon: "./images/icons/spiritSymbol.png",
        actions: [ "damage1", "damage5"],
    },
    "sp002": {
        name: "Rimuru",
        description: " A friendly blue slime with a tendency to shapeshift",
        type: SpriteTypes.sprit,
        src: "./images/sprites/spBlueSlime.png",
        icon: "./images/icons/spiritSymbol.png",
        actions: [ "damage5","damage1", "hugsStatus"],
    },
    "sp003": {
        name: "Timely Spirit",
        description: " A mutant possed clock that straddles the stream of time",
        type: SpriteTypes.sprit,
        src: "./images/sprites/spPossesedClock.png",
        icon: "./images/icons/spiritSymbol.png",
        actions: [ "damage1"],
    },
}